### ISSUE TITLE
gopher-luar source of github.com is unavailable

### ISSUE THREAD

**Issue by ysweid** [felipejfc/gluahttpscrape#1]
**Issue:**
gopher-luar package is not available on `github.com/layeh/gopher-luar`. however, it's still alive on `layeh.com/gopher-luar`

**Fix:**
gopher-luar package should be moved to `layeh.com` folder in the `vendor` folder.

A fork with the fix:
https://github.com/ysweid/gluahttpscrape/commit/b96b7c2eba73032627f3a52ce0639d6d74e7f829

**Comment by felipejfc** [comment]
can you send a PR?

**Comment by ysweid** [comment]
@felipejfc git doesn't detect the addition change in vendor folder. I moved `layeh` folder from `github.com` to `layeh.com` folder. it detected the removal from `github.com` but didn't detect the new folder `layeh.com`. any advice ?

**Comment by ysweid** [comment]
@felipejfc I read about `glide` and the issue is fixed.

**Comment by felipejfc** [comment]
fixed by https://github.com/felipejfc/gluahttpscrape/pull/2
thanks @ysweid 
closing
